# Contiki network configuration
MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET

CONTIKI_PROJECT = client basestation test-adxl345 login
APPS=serial-shell

all: $(CONTIKI_PROJECT)

CONTIKI = /home/osboxes/contiki-ng
include $(CONTIKI)/Makefile.include
